#!/usr/bin/env bash

SP_500=(\
A AAL AAPL  ABBV ABNB ABT ACGL ACN  ADBE ADI ADM ADP ADSK  AEE AEP AES \
AFL AIG AIZ AJG AKAM ALB ALGN ALL  ALLE AMAT AMCR AMD AME AMGN AMP AMT \
AMZN ANET ANSS AON AOS APA APD APH  APTV ARE ATO AVB AVGO AVY AWK AXON \
AXP AZO BA BAC BALL BAX BBWI BBY  BDX BEN BF.B BG BIIB BIO BK BKNG BKR \
BLDR BLK BMY  BR BRK.B BRO BSX BWA  BX BXP C CAG CAH CARR  CAT CB CBOE \
CBRE CCI CCL CDAY CDNS CDW CE CEG  CF CFG CHD CHRW CHTR CI CINF CL CLX \
CMA CMCSA CME  CMG CMI CMS CNC CNP  COF COO COP COR COST  CPB CPRT CPT \
CRL CRM CSCO CSGP CSX CTAS CTLT CTRA CTSH CTVA CVS CVX CZR D DAL DD DE \
DFS DG DGX DHI  DHR DIS DLR DLTR DOV DOW DPZ DRI  DTE DUK DVA DVN DXCM \
EA EBAY ECL ED EFX EG EIX EL ELV EMN EMR ENPH EOG EPAM EQIX EQR EQT ES \
ESS ETN ETR ETSY EVRG EW EXC EXPD  EXPE EXR F FANG FAST FCX FDS FDX FE \
FFIV FI FICO  FIS FITB FLT FMC FOX  FOXA FRT FSLR FTNT FTV  GD GE GEHC \
GEN GILD  GIS GL GLW GM  GNRC GOOG GOOGL GPC  GPN GRMN GS GWW  HAL HAS \
HBAN HCA HD HES HIG HII HLT HOLX HON HPE HPQ HRL HSIC HST HSY HUBB HUM \
HWM IBM ICE  IDXX IEX IFF ILMN INCY  INTC INTU INVH IP IPG  IQV IR IRM \
ISRG IT ITW  IVZ J JBHT JBL JCI  JKHY JNJ JNPR JPM K KDP  KEY KEYS KHC \
KIM KLAC KMB KMI KMX KO KR KVUE L  LDOS LEN LH LHX LIN LKQ LLY LMT LNT \
LOW LRCX LULU LUV LVS LW LYB LYV  MA MAA MAR MAS MCD MCHP MCK MCO MDLZ \
MDT MET META MGM MHK MKC MKTX MLM MMC MMM MNST MO MOH MOS MPC MPWR MRK \
MRNA MRO MS MSCI MSFT MSI MTB MTCH  MTD MU NCLH NDAQ NDSN NEE NEM NFLX \
NI NKE NOC NOW NRG NSC NTAP NTRS NUE NVDA NVR NWS NWSA NXPI O ODFL OKE \
OMC ON ORCL  ORLY OTIS OXY PANW  PARA PAYC PAYX PCAR PCG  PEAK PEG PEP \
PFE PFG PG PGR PH PHM PKG PLD PM PNC PNR PNW PODD POOL PPG PPL PRU PSA \
PSX PTC PWR PXD PYPL QCOM QRVO RCL  REG REGN RF RHI RJF RL RMD ROK ROL \
ROP ROST RSG RTX RVTY SBAC SBUX SCHW  SHW SJM SLB SNA SNPS SO SPG SPGI \
SRE STE STLD STT  STX STZ SWK SWKS SYF SYK SYY T  TAP TDG TDY TECH TEL \
TER TFC TFX TGT  TJX TMO TMUS TPR TRGP TRMB TROW TRV  TSCO TSLA TSN TT \
TTWO TXN TXT TYL UAL UBER UDR UHS  ULTA UNH UNP UPS URI USB V VFC VICI \
VLO VLTO VMC VRSK  VRSN VRTX VTR VTRS VZ WAB WAT WBA  WBD WDC WEC WELL \
WFC WHR WM  WMB WMT WRB WRK WST  WTW WY WYNN XEL XOM XRAY  XYL YUM ZBH \
ZBRA ZION ZTS \
)

COUNT=${#SP_500[@]}

# Check for TIINGO KEY.
if [[ $# -ne 1 ]];
then
	echo "Usage $0 TIINGO_KEY" >&2
	exit 2
fi

TIINGO_KEY=$1
CHUNK=50

for FROM in $(seq 0 "$CHUNK" "$COUNT");
do
	echo Sync from "$FROM" to "$TO"...
	go run cmd/indicator-sync/main.go -key "$TIINGO_KEY" -target ~/assets -days 3650 "${SP_500[@]:FROM:CHUNK}"

	echo Sleep
	sleep 1h
done

