// Copyright (c) 2021-2026 The Indicator Authors.
// The source code is provided under GNU AGPLv3 License.
// https://github.com/cinar/indicator

package volatility

import (
	"context"
	"fmt"

	"github.com/cinar/indicator/v2/helper"
	"github.com/cinar/indicator/v2/trend"
)

const (
	// DefaultDonchianChannelPeriod is the default period for the Donchian Channel.
	DefaultDonchianChannelPeriod = 20
)

// DonchianChannel represents the configuration parameters for calculating the Donchian Channel (DC). It calculates
// three lines generated by moving average calculations that comprise an indicator formed by upper and lower bands
// around a midrange or median band. The upper band marks the highest price of an asset while the lower band marks
// the lowest price of an asset, and the area between the upper and lower bands represents the Donchian Channel.
//
//	Upper Channel = Mmax(period, highs)
//	Lower Channel = Mmin(period, lows)
//	Middle Channel = (Upper Channel + Lower Channel) / 2
//
// Example:
//
//	dc := volatility.NewDonchianChannel[float64]()
//	uppers, middles, lowers := dc.Compute(highs, lows)
type DonchianChannel[T helper.Float] struct {
	// Max is the Moving Max instance.
	Max *trend.MovingMax[T]

	// Min is the Moving Min instance.
	Min *trend.MovingMin[T]
}

// NewDonchianChannel function initializes a new Donchian Channel instance with the default parameters.
func NewDonchianChannel[T helper.Float]() *DonchianChannel[T] {
	return NewDonchianChannelWithPeriod[T](DefaultDonchianChannelPeriod)
}

// NewDonchianChannelWithPeriod function initializes a new Donchian Channel instance with the given period.
func NewDonchianChannelWithPeriod[T helper.Float](period int) *DonchianChannel[T] {
	return &DonchianChannel[T]{
		Max: trend.NewMovingMaxWithPeriod[T](period),
		Min: trend.NewMovingMinWithPeriod[T](period),
	}
}

// ComputeWithContext function takes the highs and lows channels and computes the Donchian Channel over the
// specified period.
func (d *DonchianChannel[T]) ComputeWithContext(ctx context.Context, highs, lows <-chan T) (<-chan T, <-chan T, <-chan T) {
	uppers := helper.DuplicateWithContext(ctx, d.Max.ComputeWithContext(ctx, highs),
		2,
	)

	lowers := helper.DuplicateWithContext(ctx, d.Min.ComputeWithContext(ctx, lows),
		2,
	)

	middle := helper.DivideByWithContext(ctx, helper.AddWithContext(ctx, uppers[0], lowers[0]),
		2,
	)

	return uppers[1], middle, lowers[1]
}

// IdlePeriod is the initial period that Donchian Channel won't yield any results.
func (d *DonchianChannel[T]) IdlePeriod() int {
	return d.Max.IdlePeriod()
}

// String is the string representation of the Donchian Channel.
func (d *DonchianChannel[T]) String() string {
	return fmt.Sprintf("DC(%d)", d.Max.Period)
}

// Compute wraps ComputeWithContext for backwards compatibility.
//
// Deprecated: Use ComputeWithContext instead.
func (d *DonchianChannel[T]) Compute(highs, lows <-chan T) (<-chan T, <-chan T, <-chan T) {
	return d.ComputeWithContext(context.Background(), highs, lows)
}
