// Copyright (c) 2021-2026 The Indicator Authors.
// The source code is provided under GNU AGPLv3 License.
// https://github.com/cinar/indicator

package decorator

import (
	"fmt"

	"context"

	"github.com/cinar/indicator/v2/asset"
	"github.com/cinar/indicator/v2/helper"
	"github.com/cinar/indicator/v2/strategy"
)

// InverseStrategy demonstrates an illustrative decorator that inverts the
// actions generated by an underlying strategy.
type InverseStrategy struct {
	// InnerStrategy is the inner strategy.
	InnerStrategy strategy.Strategy
}

// NewInverseStrategy initializes an example InverseStrategy instance with default parameters.
func NewInverseStrategy(innerStrategy strategy.Strategy) *InverseStrategy {
	return &InverseStrategy{
		InnerStrategy: innerStrategy,
	}
}

// Name returns the name of the example strategy.
func (i *InverseStrategy) Name() string {
	return fmt.Sprintf("Inverse Strategy (%s)", i.InnerStrategy.Name())
}

// ComputeWithContext processes the provided asset snapshots and generates an illustrative stream of actions.
func (i *InverseStrategy) ComputeWithContext(ctx context.Context, snapshots <-chan *asset.Snapshot) <-chan strategy.Action {
	return helper.MapWithContext(ctx, strategy.ComputeStrategyWithContext(ctx, i.InnerStrategy, snapshots), func(action strategy.Action) strategy.Action {
		switch action {
		case strategy.Buy:
			return strategy.Sell

		case strategy.Sell:
			return strategy.Buy

		default:
			return strategy.Hold
		}
	})
}

// Report processes the provided asset snapshots and generates an illustrative report annotated with example actions.
func (i *InverseStrategy) Report(c <-chan *asset.Snapshot) *helper.Report {
	snapshots := helper.Duplicate(c, 3)

	dates := asset.SnapshotsAsDates(snapshots[0])
	closings := asset.SnapshotsAsClosings(snapshots[1])

	actions, outcomes := strategy.ComputeWithOutcome(i, snapshots[2])
	annotations := strategy.ActionsToAnnotations(actions)
	outcomes = helper.MultiplyBy(outcomes, 100)

	report := helper.NewReport(i.Name(), dates)
	report.AddChart()

	report.AddColumn(helper.NewNumericReportColumn("Close", closings))
	report.AddColumn(helper.NewAnnotationReportColumn(annotations))

	report.AddColumn(helper.NewNumericReportColumn("Outcome", outcomes), 1)

	return report
}

// Compute wraps ComputeWithContext for backwards compatibility.
//
// Deprecated: Use ComputeWithContext instead.
func (i *InverseStrategy) Compute(snapshots <-chan *asset.Snapshot) <-chan strategy.Action {
	return i.ComputeWithContext(context.Background(), snapshots)
}
