name: Doc update

on:
  push:
    branches: [master]

permissions:
  contents: read

jobs:

  docgen:
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      run: go install github.com/princjef/gomarkdoc/cmd/gomarkdoc@latest
    - uses: actions/checkout@v4
    - name: Run gomarkdoc
      run: |
        gomarkdoc --output helper/README.md ./helper
        git diff .
